# Toxic Comment classification competition
https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge/data

In [41]:
import numpy as np
import pandas as pd
import tensorflow as tf

from nltk.tokenize import word_tokenize

In [39]:
df = pd.read_csv("data/train.csv")

In [40]:
df.head(n=100)

id                                       comment_text  \
0   0000997932d777bf  Explanation\nWhy the edits made under my usern...   
1   000103f0d9cfb60f  D'aww! He matches this background colour I'm s...   
2   000113f07ec002fd  Hey man, I'm really not trying to edit war. It...   
3   0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...   
4   0001d958c54c6e35  You, sir, are my hero. Any chance you remember...   
5   00025465d4725e87  "\n\nCongratulations from me as well, use the ...   
6   0002bcb3da6cb337       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK   
7   00031b1e95af7921  Your vandalism to the Matt Shirvington article...   
8   00037261f536c51d  Sorry if the word 'nonsense' was offensive to ...   
9   00040093b2687caa  alignment on this subject and which are contra...   
10  0005300084f90edc  "\nFair use rationale for Image:Wonju.jpg\n\nT...   
11  00054a5e18b50dd4  bbq \n\nbe a man and lets discuss it-maybe ove...   
12  0005c987bdfc9d4b  Hey... what is it..\n@ | talk .\nWhat is it......   
13  0006f16e4e9f292e  Before you start throwing accusations and warn...   
14  00070ef96486d6f9  Oh, and the girl above started her arguments w...   
15  00078f8ce7eb276d  "\n\nJuelz Santanas Age\n\nIn 2002, Juelz Sant...   
16  0007e25b2121310b  Bye! \n\nDon't look, come or think of comming ...   
17  000897889268bc93   REDIRECT Talk:Voydan Pop Georgiev- Chernodrinski   
18  0009801bd85e5806  The Mitsurugi point made no sense - why not ar...   
19  0009eaea3325de8c  Don't mean to bother you \n\nI see that you're...   
20  000b08c464718505  "\n\n Regarding your recent edits \n\nOnce aga...   
21  000bfd0867774845  "\nGood to know. About me, yeah, I'm studying ...   
22  000c0dfd995809fa  "\n\n Snowflakes are NOT always symmetrical! \...   
23  000c6a3f0cd3ba8e  "\n\n The Signpost: 24 September 2012 \n\n Rea...   
24  000cfee90f50d471  "\n\nRe-considering 1st paragraph edit?\nI don...   
25  000eefc67a2c930f  Radial symmetry \n\nSeveral now extinct lineag...   
26  000f35deef84dc4a  There's no need to apologize. A Wikipedia arti...   
27  000ffab30195c5e1  Yes, because the mother of the child in the ca...   
28  0010307a3a50a353  "\nOk. But it will take a bit of work but I ca...   
29  0010833a96e1f886  "== A barnstar for you! ==\n\n  The Real Life ...   
..               ...                                                ...   
70  002a13f2896596fa  "\n\nOppose – As the article stands, it does n...   
71  002a6beca33307b3  I would appreciate an apology from both of you...   
72  002b90cc8a94c76b  They are NOT original research, they are point...   
73  002c9cccf2f1d05b  "\n Ambiguous ? \nSo Mabuska Irish can mean mo...   
74  002d6c9d9f85e81f  "\nWhile the magazine's masthead says ""TIME""...   
75  002e2d3db2b597c4  Take your belated and piffling prevarications ...   
76  002f0e29c60807b1  That's what I'm looking through, it looks like...   
77  0030614cfd96d9d1  In the same direction, is it really necessary ...   
78  00316bcc0d1bc6e0  , 20 December 2006 (UTC)\n\nYou must not play ...   
79  003217c3eb469ba9  Hi! I am back again!\nLast warning!\nStop undo...   
80  00328eadb85b3010  "\n\nMinimization of textile effluent\n\nA pro...   
81  0033b9d5ccd499fb  "\n\nIs it scientific to attribute an event A,...   
82  0034065c7b12a7a2  Screwjob \n\n   Hey i noticed your comments on...   
83  00349c6325526c11  April 2006\nThank you for experimenting with t...   
84  0034d7c78cfa6dee  "\n\nChrist. ""IQ is selected for therefore ev...   
85  0035d638ba684122  Can you prove it isn't ? If you had a better k...   
86  0036621e4c7e10b5  Would you both shut up, you don't run wikipedi...   
87  0036e50f42d0b679    Oh, it's me vandalising?xD See here. Greetings,   
88  0037e59caead9dab  Website \n\nHey all,\nI was thinking of gettin...   
89  0037fe4f8f5cdcfb                         Thanks reading there now !   
90  0038d1dc2ad29469  Personal attacks in Fruit Brute VfD \n\nMy apo...   
91  0038f191ffc93d75  Transliteration of Ru

In [51]:
df = df.assign(text_length=df['comment_text'].apply(lambda x: len(word_tokenize(x))))

In [57]:
df = df.assign(char_length=df['comment_text'].apply(lambda x: len(x)))

In [59]:
df = df.assign(num_cap_char=df['comment_text'].apply(lambda x: sum(map(str.isupper, x))))

In [61]:
df = df.assign(upper_prop=df.num_cap_char/df.char_length)

In [62]:
df

id                                       comment_text  \
0       0000997932d777bf  Explanation\nWhy the edits made under my usern...   
1       000103f0d9cfb60f  D'aww! He matches this background colour I'm s...   
2       000113f07ec002fd  Hey man, I'm really not trying to edit war. It...   
3       0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...   
4       0001d958c54c6e35  You, sir, are my hero. Any chance you remember...   
5       00025465d4725e87  "\n\nCongratulations from me as well, use the ...   
6       0002bcb3da6cb337       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK   
7       00031b1e95af7921  Your vandalism to the Matt Shirvington article...   
8       00037261f536c51d  Sorry if the word 'nonsense' was offensive to ...   
9       00040093b2687caa  alignment on this subject and which are contra...   
10      0005300084f90edc  "\nFair use rationale for Image:Wonju.jpg\n\nT...   
11      00054a5e18b50dd4  bbq \n\nbe a man and lets discuss it-maybe ove...   
12      0005c987bdfc9d4b  Hey... what is it..\n@ | talk .\nWhat is it......   
13      0006f16e4e9f292e  Before you start throwing accusations and warn...   
14      00070ef96486d6f9  Oh, and the girl above started her arguments w...   
15      00078f8ce7eb276d  "\n\nJuelz Santanas Age\n\nIn 2002, Juelz Sant...   
16      0007e25b2121310b  Bye! \n\nDon't look, come or think of comming ...   
17      000897889268bc93   REDIRECT Talk:Voydan Pop Georgiev- Chernodrinski   
18      0009801bd85e5806  The Mitsurugi point made no sense - why not ar...   
19      0009eaea3325de8c  Don't mean to bother you \n\nI see that you're...   
20      000b08c464718505  "\n\n Regarding your recent edits \n\nOnce aga...   
21      000bfd0867774845  "\nGood to know. About me, yeah, I'm studying ...   
22      000c0dfd995809fa  "\n\n Snowflakes are NOT always symmetrical! \...   
23      000c6a3f0cd3ba8e  "\n\n The Signpost: 24 September 2012 \n\n Rea...   
24      000cfee90f50d471  "\n\nRe-considering 1st paragraph edit?\nI don...   
25      000eefc67a2c930f  Radial symmetry \n\nSeveral now extinct lineag...   
26      000f35deef84dc4a  There's no need to apologize. A Wikipedia arti...   
27      000ffab30195c5e1  Yes, because the mother of the child in the ca...   
28      0010307a3a50a353  "\nOk. But it will take a bit of work but I ca...   
29      0010833a96e1f886  "== A barnstar for you! ==\n\n  The Real Life ...   
...                  ...                                                ...   
159541  ffa33d3122b599d6  Your absurd edits \n\nYour absurd edits on gre...   
159542  ffa95244f261527f  maybe he's got better things to do than spend ...   
159543  ffad104337fe9891  scrap that, it does meet criteria and its gone...   
159544  ffaed63c487a2b42                                You could do worse.   
159545  ffb268f37788a011  , 7 March 2011 (UTC)\nAre you also User:Bmatts...   
159546  ffb47123b2d82762  "\n\nHey listen don't you ever!!!! Delete my e...   
159547  ffb7b4c3d3ae5842                     Thank you very, very much.  ·✆   
159548  ffb93b0a0a1e78f9                        Talkback: 15 September 2012   
159549  ffb998f9749bd83e                         2005 (UTC)\n 06:35, 31 Mar   
159550  ffba5332d6b8fd14  i agree/ on another note lil wayne is a talent...   
159551  ffbc2db4225258dd  While about half the references are from BYU-I...   
159552  ffbcd64a71775e04  Prague Spring \n\nI think that Prague Spring d...   
159553  ffbd331a3aa269b9  I see this as having been merged; undoing one ...   
159554  ffbdbb0483ed0841  and i'm going to keep posting the stuff u dele...   
159555  ffc2f409658571f1  "\n\nHow come when you download that MP3 it's ...   
159556  ffc671f2acdd80e1  I'll be on IRC, too, if you have a more specif...   
159557  ffc7bbb177c3c966  It is my opinion that that happens to be off-t...   
159558  ffca1e81aefc48ac  Please stop removing content from Wikipedia; i...   
159559  ffca8d71d71a3fae  Image:Barack-obama-mother.jpg listed for delet

In [5]:
# Size of data
df.shape

(159571, 8)

In [67]:
max_length = df['text_length'].max()

In [79]:
df.loc[df['text_length'].argmax(), 'comment_text']

'YOU!\nYou blocked me worm why!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [6]:
# Show the number of comments of different levels
print(df.iloc[:,2:].apply(sum))

toxic            15294
severe_toxic      1595
obscene           8449
threat             478
insult            7877
identity_hate     1405
dtype: int64


# Preprocess the data

In [9]:
# Tokenization by using 
samples = df.loc[:5, 'comment_text']

In [13]:


word_tokenize(samples[0])

['Explanation',
 'Why',
 'the',
 'edits',
 'made',
 'under',
 'my',
 'username',
 'Hardcore',
 'Metallica',
 'Fan',
 'were',
 'reverted',
 '?',
 'They',
 'were',
 "n't",
 'vandalisms',
 ',',
 'just',
 'closure',
 'on',
 'some',
 'GAs',
 'after',
 'I',
 'voted',
 'at',
 'New',
 'York',
 'Dolls',
 'FAC',
 '.',
 'And',
 'please',
 'do',
 "n't",
 'remove',
 'the',
 'template',
 'from',
 'the',
 'talk',
 'page',
 'since',
 'I',
 "'m",
 'retired',
 'now.89.205.38.27']

In [21]:
import tensorflow as tf

vocab_processor = tf.contrib.learn.preprocessing.VocabularyProcessor(50)

transformed = vocab_processor.fit_transform(samples)

In [80]:
sess = tf.InteractiveSession()

In [81]:
x = tf.constant([1, 2, 3])

In [82]:
tf.shape(x)

<tf.Tensor 'Shape:0' shape=(1,) dtype=int32>

In [83]:
sess.run(tf.expand_dims(x, -1))

array([[1],
       [2],
       [3]], dtype=int32)

In [84]:
sess.run(tf.shape(tf.expand_dims(x, -1)))

array([3, 1], dtype=int32)

In [22]:
list(transformed)

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,  3,
        34, 35,  3, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,  0,  0,  0]),
 array([46, 47, 48, 49, 50, 51, 39, 52, 53, 54, 55, 36, 56, 57, 58, 59, 60,
        61,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]),
 array([62, 63, 39, 64, 65, 66, 67, 68, 69, 70, 17, 71, 49, 72, 73, 74, 75,
        76, 77, 78, 79, 67, 80, 81,  4, 82, 83,  7, 36, 37, 47, 84, 67, 85,
        86, 87,  3, 88, 89,  3, 90, 91,  0,  0,  0,  0,  0,  0,  0,  0]),
 array([ 92,  23,  93,  94,  95,  96,  97,  19,  98,  99,  23, 100, 101,
          3, 102, 103, 104, 105, 106,  19, 107, 108, 109,  83, 110,  83,
        111, 112, 113,   3, 114, 115, 116, 117, 118,  71, 119, 120, 121,
        122,   3, 123, 124, 125, 126, 127, 125, 128,  23, 129]),
 array([163, 164, 120,   7, 165, 166, 

In [28]:
print(vocab_processor.vocabulary_._mapping)

{'<UNK>': 0, 'Explanation': 1, 'Why': 2, 'the': 3, 'edits': 4, 'made': 5, 'under': 6, 'my': 7, 'username': 8, 'Hardcore': 9, 'Metallica': 10, 'Fan': 11, 'were': 12, 'reverted': 13, 'They': 14, "weren't": 15, 'vandalisms': 16, 'just': 17, 'closure': 18, 'on': 19, 'some': 20, 'GAs': 21, 'after': 22, 'I': 23, 'voted': 24, 'at': 25, 'New': 26, 'York': 27, 'Dolls': 28, 'FAC': 29, 'And': 30, 'please': 31, "don't": 32, 'remove': 33, 'template': 34, 'from': 35, 'talk': 36, 'page': 37, 'since': 38, "I'm": 39, 'retired': 40, 'now': 41, '89': 42, '205': 43, '38': 44, '27': 45, "D'aww": 46, 'He': 47, 'matches': 48, 'this': 49, 'background': 50, 'colour': 51, 'seemingly': 52, 'stuck': 53, 'with': 54, 'Thanks': 55, '21': 56, '51': 57, 'January': 58, '11': 59, '2016': 60, 'UTC': 61, 'Hey': 62, 'man': 63, 'really': 64, 'not': 65, 'trying': 66, 'to': 67, 'edit': 68, 'war': 69, "It's": 70, 'that': 71, 'guy': 72, 'is': 73, 'constantly': 74, 'removing': 75, 'relevant': 76, 'information': 77, 'and': 78, 't